-- Create the inquiries table
create table inquiries (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  company text,
  phone text,
  email text,
  sns text,
  channel text,
  plan text,
  message text,
  status text default 'new'
);

-- Enable Row Level Security (RLS)
alter table inquiries enable row level security;

-- Create a policy that allows anyone to insert (since it's a public form)
create policy "Enable insert for everyone" on inquiries for insert with check (true);

-- Create a policy that allows only authenticated users (admins) to select
-- For simplicity in this MVP, we might allow public select if RLS is tricky, 
-- BUT for security, you should restrict this. 
-- However, since we are using the anon key in the server-side API route (Next.js App Router),
-- the API route acts as a backend. 
-- If you are using the Service Role Key, you bypass RLS.
-- If you are using Anon Key, you need policies.

-- For this specific project setup where we use the same client for everything:
create policy "Enable select for everyone" on inquiries for select using (true);

-- Create policy for update
create policy "Enable update for everyone" on inquiries for update using (true);
